#!/bin/bash

for file in /Users/jjbook/Documents/JJ/projects/my-apps/*; do
    if [ -d "$file" ]
    then
        echo "$file is a directory"
    elif [ -f "$file" ]
    then
        echo "$file is a file"
    else
        echo "$file others"
    fi
done











