#!/bin/zsh

# file=t15test
# touch $file

# if [ -s $file ]
# then
#     echo "The $file file exists and has data in it"
# else
#     echo "The $file exists and is empty"
# fi

# date > $file

# if [ -s $file ]
# then
#     echo "The $file file exists and has data in it"
# else
#     echo "The $file exists and is empty"
# fi

var1=5
while [ $var1 -ge 0 ]
do
    echo "Outer loop: $var1"
    for (( var2 = 1; var2 < 3; var2++  ))
    do
        var3=$[ $var1 * $var2 ]
        echo "Inner loop: $var1 * $var2 = $var3"
    done
    var1=$[ $var1- 1 ]
done
