#!/bin/zsh

case $USER in
rich | barbara)
    echo "Welcome, $USER"
    echo "Please enjoy your visit";;
testing)
    echo "Special testing account";;
jessica)
    echo "Don't forget t o log off when you're done";;
*)
    echo "Sorry, you're not allowed here";;
esac
