#!/bin/bash

# if [ -d $HOME ]
# then
#     echo "Your HOME directory exists"
#     cd $HOME
#     ls -a
# else
#     echo "There's a problem with Your HOME directory"
# fi

# var1=10
# while echo $var1
#     [ $var1 -ge 0 ]
# do
#     echo "This is inside the loop"
#     var1=$[ $var1 -1 ]
# done


